#!/bin/bash
# Copyright (c) 2017-2026 Jean-Louis Leroy
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt
# or copy at http://www.boost.org/LICENSE_1_0.txt)

# Check the headers generated by dev/flatten.py: each one must compile after the
# root, fail with our own diagnostic without it, and the ce/ examples must build
# and run against the generated tree.
#
# Usage: BOOST_SRC_DIR=/path/to/boost dev/check-flat.sh [output-dir]

set -uo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
flat_dir="${1:-$root_dir/flat}"
boost_dir="${BOOST_SRC_DIR:-$root_dir/../..}"
cxx="${CXX:-g++}"
cxxstd="${CXXSTD:--std=c++17}"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# A modular tree (libs/*/include) is what CI clones; a monolithic one has the
# headers under boost/. Prefer the former: the latter can be a stale b2 headers
# tree.
if [ -d "$boost_dir/libs" ]; then
    boost_includes=()
    for dir in "$boost_dir"/libs/*/include "$boost_dir"/libs/numeric/*/include; do
        [ -d "$dir" ] && boost_includes+=("-I$dir")
    done
else
    boost_includes=("-I$boost_dir")
fi

python3 "$root_dir/dev/flatten.py" \
    --include-dir "$root_dir/include" --output-dir "$flat_dir" > /dev/null || exit 1

compile=("$cxx" "$cxxstd" "-I$flat_dir" "${boost_includes[@]}")
status=0

report() {
    printf '%-6s %s\n' "$1" "$2"
    [ "$1" = ok ] || status=1
}

cd "$flat_dir" || exit 1

for header in $(find boost -name '*.hpp' | sort); do
    if [ "$header" = boost/openmethod.hpp ]; then
        printf '#include <%s>\n' "$header" > "$work/tu.cpp"
    else
        printf '#include <boost/openmethod.hpp>\n#include <%s>\n' "$header" \
            > "$work/tu.cpp"
    fi

    if "${compile[@]}" -fsyntax-only "$work/tu.cpp" > "$work/log" 2>&1; then
        report ok "$header"
    else
        report FAIL "$header"
        head -20 "$work/log"
    fi

    grep -q '^#error' "$header" || continue

    # Without the root, the guard checks must fire.
    printf '#include <%s>\n' "$header" > "$work/tu.cpp"

    if "${compile[@]}" -fsyntax-only "$work/tu.cpp" > "$work/log" 2>&1; then
        report FAIL "$header (alone: expected an error)"
    elif grep -q 'openmethod.hpp> first' "$work/log"; then
        report ok "$header (alone)"
    else
        report FAIL "$header (alone: not our diagnostic)"
        head -20 "$work/log"
    fi
done

cd "$root_dir" || exit 1

for source in ce/*.cpp; do
    example="$work/$(basename "$source" .cpp)"

    if ! "${compile[@]}" -O2 -o "$example" "$source" > "$work/log" 2>&1; then
        report FAIL "$source"
        head -20 "$work/log"
        continue
    fi

    if "$example" > /dev/null; then
        report ok "$source"
    else
        report FAIL "$source (run)"
    fi
done

exit $status
