:example: ../examples

= Boost.OpenMethod

Boost.OpenMethod is a C++17 library that implements open-methods.

== Features

* Headers-only.

* Single-virtual-argument method calls are as fast as equivalent virtual
function calls. Multi-methods are dispatched in constant time.

* Redundancy-free multiple dispatch tables.

* Exception agnostic by default.

* Customization points for alternative RTTI systems, error handling, vptr
placement, etc.

== Requirements

The library requires a compiler supporting C++17 or above.

== Tested Compilers

Boost.OpenMethod has been tested with the following compilers:

* clang: 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20

* gcc: 8, 9, 10, 11, 12, 13, 14, 15

* msvc: 14.3

and on the following platforms:

* Linux

* macOS

* Windows

== Quality Assurance

The development infrastructure for the library includes these per-commit
analyses:

* Coverage reports

* Clang sanitizers

* Compilation and tests on Drone.io and GitHub Actions

== Acknowledgments

I would like to thank the C++ Alliance for their support, in particular Joaquín
M. López Muñoz for encouraging me to submit my library and being the first to
endorse it; and Dmitryi Arkhipov for volunteering to be the review manager.

Thanks to the members of the Boost community who posted a formal review:

* Joaquin M López Muñoz,

* Christian Mazakas,

* Ruben Perez,

* Yannick Le Goc,

* Klemens Morgenstern,

* Andrzej Krzemienski.

Also thanks to Steven Watanabe for his cogent feedback and advice, and all the
people who posted comments and remarks.

This work was strongly influenced by the following papers:

* https://www.stroustrup.com/multimethods.pdf[Open Multi-Methods for C++], Peter
Pirkelbauer, Yuri Solodkyi and Bjarne Stroustrup

* https://core.ac.uk/download/pdf/18599789.pdf[Simplifying the Analysis of C++
Programs], Yuriy Solodkyy.

* http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2216.pdf[Report on
language support for Multi-Methods and Open-Methods for C++], Peter Pirkelbauer,
Yuri Solodkyi and Bjarne Stroustrup.

* https://dl.acm.org/doi/abs/10.1145/191081.191117[Optimizing multi-method
dispatch using compressed dispatch tables], Eric Amiel, Olivier Gruber and Eric
Simon.

Finally, thanks to Prof J.D. Garcia for organizing the "using std::cpp"
conference, and introducing me to Joaquín.
