[#troubleshooting]

:example: troubleshooting
:tabs-sync-option:

### Compilation Errors

OpenMethod is a library that emulates a language feature. Unfortunately, it
cannot produce diagnostics as good as what a compiler can. Compilation errors
often take the form of template instantiation failures, which can be hard to
decipher. However, most compilation errors can be traced back to a few common
mistakes, which have their typical signature.

The most frequent error a novice user is likely to encounter is a failure to
match an overrider to a method.

[source,c++]
----
include::{example}/match_no_method.cpp[tag=content]
----

The error here is obvious: we are defining an overrider for a method that was
notr declared. The message varies between compilers; in all cases it is very
lengthy, and includes stack traces of template instantiations and macro
expansions. The important bit is in the first lines of the error:

[tabs]
======
clang::
+
```
use of undeclared identifier 'poke_boost_openmethod_guide'
```

gcc::
+
```
‘poke_boost_openmethod_guide’ was not declared in this scope; did you mean ‘poke_boost_openmethod_overriders’?
```

msvc::
+
```
'poke_boost_openmethod_guide': identifier not found
```
======

`poke_boost_openmethod_guide` is a function generated by `BOOST_OPENMETHOD`.
`BOOST_OPENMETHOD_OVERRIDE` attempts to call it (in a non-evaluated context);
its return type is an instantiation of cpp:method[]. It may be found either in
the current scope, or via argument-dependent lookup (ADL).

If the method exists, but it cannot be located, the error message is similar.
For example:

[source,c++]
----
include::{example}/match_method_not_visible.cpp[tag=content]
----

The error is slightly different, but again it is about not finding the guide
function.

[tabs]
======
clang::
+
```
error: no matching function for call to 'poke_boost_openmethod_guide'
```

gcc::
+
```
error: no matching function for call to ‘poke_boost_openmethod_guide(boost::openmethod::virtual_ptr<animals::Cat>&)’
```

msvc::
+
```
error C2672: 'poke_boost_openmethod_guide': no matching overloaded function found
```
======

In these two cases, the error is pretty obvious.

### Runtime Errors
