[#troubleshooting]

:tabs-sync-option:

// include::{examplesdir}/troubleshooting/fragments.adoc[]


### Compilation errors

OpenMethod is a library that emulates a language feature. Unfortunately, it
cannot produce diagnostics as good as what a compiler can. Compilation errors
often take the form of template instantiation failures, which can be hard to
decipher. However, most compilation errors can be traced back to a few common
mistakes, which have their typical signature.

Note;; Error outputs are clipped after the line that identifies the cause of the
error.

#### BOOST_OPENMETHOD_OVERRIDE fails to match a method

`BOOST_OPENMETHOD_OVERRIDE` automatically determines which method the overrider
if for. Failure to find a method results in an error message in the macro
expansion. In contains a function named after the method, with a
`_boost_openmethod_guide` suffix.

Example:

[source,c++]
----
include::{examplesdir}/troubleshooting/override_no_method.cpp[tag=content]
----

Error:

include::{examplesdir}/troubleshooting/override_no_method.adoc[]

The method does not exist.

Example:

[source,c++]
----
include::{examplesdir}/troubleshooting/override_no_conversion.cpp[tag=content]
----

Error:

include::{examplesdir}/troubleshooting/override_no_conversion.adoc[]

`Plus` derives from `Node` _privately_. There is no conversion from
`virtual_ptr<Plus>` to `virtual_ptr<Node>`. `postfix` cannot be called with a
`virtual_ptr<Plus>`.

#### Method cannot be called

Virtual arguments can be passed to method calls as references or pointers. This
relies on `virtual_ptr`{empty}'s conversion constructor. If its requirements are
not met, the constructor does not exist.

Example:
[source,c++]
----
include::{examplesdir}/troubleshooting/call_not_polymorphic.cpp[tag=content]
----

Error:
include::{examplesdir}/troubleshooting/call_not_polymorphic.adoc[]

`virtual_ptr` requires the type to be polymorphic (according to the method's
rtti policy) for the conversion to exist.

### Runtime errors

#### Missing or incorrect class registrations

Classes involved in virtual parameters must be registered.

Example:
[source,c++]
----
include::{examplesdir}/troubleshooting/use_classes_missing_class.cpp[tag=content]
----

Error:
include::{examplesdir}/troubleshooting/use_classes_missing_class.adoc[]

All the direct bases of a class must appear in the same registration as the
class itself.

Example:
[source,c++]
----
include::{examplesdir}/troubleshooting/use_classes_missing_base.cpp[tag=content]
----

Error:
include::{examplesdir}/troubleshooting/use_classes_missing_base.adoc[]

`initialize` deduces from the overrider that `Variable` derives from `Node`, but
`Node` and `Variable` do not appear together in
`BOOST_OPENMETHOD_REGISTER_CLASSES`.

Classes that are used as virtual arguments must be registered as well as classes
in virtual parameters. Failure to do so results in SEGV, or the wrong overrider
may be called. Compiling with `BOOST_OPENMETHOD_ENABLE_RUNTIME_CHECKS` defined
enables checks for this problem. This is recommended for debug builds.

Example:
[source,c++]
----
include::{examplesdir}/troubleshooting/use_classes_missing_class_call.cpp[tag=content]
----

Note that `Bulldog` is not registered.

Error (with `BOOST_OPENMETHOD_ENABLE_RUNTIME_CHECKS` defined):
include::{examplesdir}/troubleshooting/use_classes_missing_class_call.adoc[]
