[#troubleshooting]

:tabs-sync-option:

### Compilation Errors

OpenMethod is a library that emulates a language feature. Unfortunately, it
cannot produce diagnostics as good as what a compiler can. Compilation errors
often take the form of template instantiation failures, which can be hard to
decipher. However, most compilation errors can be traced back to a few common
mistakes, which have their typical signature.

#### BOOST_OPENMETHOD_OVERRIDE Fails to Match a Method

`BOOST_OPENMETHOD_OVERRIDE` determines which method to add the overrider to. For
that purpose, `BOOST_OPENMETHOD` generates a guide function named after the
method. It takes the same parameters as the method, and returns the
instantiation of template cpp:method[] for the method being defined.
`BOOST_OPENMETHOD_OVERRIDE` attempts to call that function (in a non-evaluated
context) with its own parameters to locate the method.

Failure to locate the method causes a compilation error. It is characteriezed by
the mention of a function with a `_boost_openmethod_guide` suffix.

This can happen because the method simply doesn't exist:

[source,c++]
----
include::{examplesdir}/troubleshooting/match_no_method.cpp[tag=content]
----

The error message is:

include::{examplesdir}/troubleshooting/match_no_method.adoc[]

Note;; Error outputs are clipped after the line that identifies the cause of the
error.

If the method exists, but it cannot be located, even via Argument-Dependent
Lookup (ADL), the error message is similar:


[source,c++]
----
include::{examplesdir}/troubleshooting/match_method_not_visible.cpp[tag=content]
----

include::{examplesdir}/troubleshooting/match_method_not_visible.adoc[]


### Runtime Errors

#### Missing or Incorrect Class Registrations

Classes involved in virtual parameters must be registered.

[source,c++]
----
include::{examplesdir}/troubleshooting/use_classes_missing_class.cpp[tag=content]
----

include::{examplesdir}/troubleshooting/use_classes_missing_class.adoc[]
